'use client'

import React from 'react'
import { useScrollReveal } from '@/hooks/useScrollReveal'
import { useCharReveal } from '@/hooks/useCharReveal'

interface Photo {
  id: string
  alt: string
  caption: string
  videoSrc?: string
  imageSrc?: string
  poster?: string
}

const PHOTOS: Photo[] = [
  { id: 'facility-1', alt: 'スタジオ全景 — 広々とした創作スペース', caption: 'メインスタジオ', videoSrc: '/videos/facility-1.webm' },
  { id: 'facility-2', alt: '3DCG制作ブース', caption: '3DCGブース', videoSrc: '/videos/facility-2.webm' },
  { id: 'facility-3', alt: '音楽制作スタジオ', caption: '音楽スタジオ', videoSrc: '/videos/facility-3.webm' },
  { id: 'facility-4', alt: 'リラックスできるラウンジスペース', caption: 'ラウンジ', videoSrc: '/videos/facility-4.webm' },
  { id: 'facility-5', alt: '展示スペース — 作品を飾る白い壁', caption: '展示ギャラリー', videoSrc: '/videos/facility-5.webm' },
]

function PhotoCard({ photo, isHero = false }: { photo: Photo; isHero?: boolean }) {
  return (
    <div
      data-facility-photo
      data-hero={isHero ? 'true' : undefined}
      className="relative overflow-hidden rounded-2xl bg-[var(--color-surface)] group w-full h-full"
    >
      {/* Shimmer placeholder — always visible until video/image loads */}
      <div className="shimmer absolute inset-0" />

      {/* Native video — shown once .webm is generated by pipeline */}
      {photo.videoSrc && (
        <video
          autoPlay
          muted
          loop
          playsInline
          poster={photo.poster ?? `/videos/${photo.id}-poster.jpg`}
          aria-label={photo.alt}
          className="absolute inset-0 w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
        >
          <source src={photo.videoSrc} type="video/webm" />
        </video>
      )}

      {/* Static image fallback */}
      {!photo.videoSrc && photo.imageSrc && (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={photo.imageSrc}
          alt={photo.alt}
          className="absolute inset-0 w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
        />
      )}

      {/* Hover caption overlay */}
      <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6">
        <p className="text-white font-semibold text-sm tracking-wide">{photo.caption}</p>
      </div>
    </div>
  )
}

export default function FacilitySection() {
  const sectionRef = useScrollReveal('.reveal')
  const charRef = useCharReveal({ type: 'words', stagger: 0.025 })

  const setRef = (el: HTMLElement | null) => {
    ;(sectionRef as React.MutableRefObject<HTMLElement | null>).current = el
    ;(charRef as React.MutableRefObject<HTMLElement | null>).current = el
  }

  return (
    <section
      ref={setRef}
      aria-label="施設案内"
      role="region"
      id="facility"
      className="py-24 px-6 relative z-10 overflow-hidden"
    >
      <div className="max-w-6xl mx-auto">
        {/* Section header */}
        <div className="mb-12">
          <p className="reveal text-xs font-medium tracking-widest uppercase text-[var(--color-accent)] mb-3">
            Facility
          </p>
          <div className="mb-4">
            <div className="accent-line is-revealed" />
          </div>
          <h2 className="char-reveal font-display text-4xl md:text-5xl font-bold text-gradient-purple mb-4">
            施設案内
          </h2>
          <p className="char-reveal text-[var(--color-text-muted)] max-w-xl">
            千葉市内の広々としたスタジオで、3DCG・音楽・映像制作に集中できる環境を整えています。
          </p>
        </div>

        {/* Hero + Asymmetric Grid */}
        <div data-facility-grid className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {/* Row 1: Hero full-width */}
          <div className="md:col-span-3 h-[420px] md:h-[480px]">
            <PhotoCard photo={PHOTOS[0]} isHero />
          </div>

          {/* Row 2: narrow + wide */}
          <div className="h-[240px]">
            <PhotoCard photo={PHOTOS[1]} />
          </div>
          <div className="md:col-span-2 h-[240px]">
            <PhotoCard photo={PHOTOS[2]} />
          </div>

          {/* Row 3: wide + narrow */}
          <div className="md:col-span-2 h-[240px]">
            <PhotoCard photo={PHOTOS[3]} />
          </div>
          <div className="h-[240px]">
            <PhotoCard photo={PHOTOS[4]} />
          </div>
        </div>
      </div>
    </section>
  )
}
